name: isen_ouest_companion
description: Companion app for the ISEN students
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.17.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    intl: ^0.17.0
    cryptography: ^2.0.5
    cryptography_flutter: ^2.0.2
    isen_aurion_client: ^1.2.2
    flutter_svg: ^1.1.4
    requests: ^4.7.0
    universal_html: ^2.0.8
    flutter_secure_storage: ^6.0.0
    table_calendar: ^3.0.7

    # personal packages
    progress_hud:
        path: packages/progress_hud
    route_creator:
        path: packages/route_creator

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    hive_generator: ^1.1.3
    build_runner: ^2.2.0
    flutter_launcher_icons: ^0.10.0

flutter_icons:
    android: true
    ios: true
    image_path: "assets/launcher_icon/icon.png" # Provide icon for ios
    adaptive_icon_background: "assets/launcher_icon/background-layer.png"
    adaptive_icon_foreground: "assets/launcher_icon/foreground-layer.png"
    web:
        generate: true
        image_ppath: "assets/launcher_icon/icon.png"
        background_color: "#FFFFFF"
        theme_color: "#4D4955"

flutter:
    uses-material-design: true

    assets:
        - assets/images/logo_hat.svg