name: custom_go_route
publish_to: none
version: 1.0.0

environment:
    sdk: ">=2.17.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
        
    go_router: ^5.0.5

    progress_hud:
        path: ../progress_hud

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
