name: progress_hud
publish_to: none
version: 2.1.0

environment:
    sdk: ">=2.17.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    flutter_progress_hud: ^2.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
