name: Build apk for android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_JKS: ${{ secrets.KEY_JKS }} # base64 android/key.jks | tr -d '\n'
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Import sign key
      run: echo $KEY_JKS | base64 -d > android/key.jks

    - name: Install Flutter
      uses: subosito/flutter-action@v2.6.2
      with:
        flutter-version: '3.3.0'

    - name: Get dependencies
      run: flutter pub get

    - name: Build release apk
      run: flutter build apk --release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
